version: "3.7"
services:
  database_ignite:
    image: postgres
    ports: 
      - 5432:5432
    container_name: database_ignite
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rentx
    volumes:
      - ./pgdata:/data/postgres


  app:
    build: 
      context: .
      network: host
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on: 
      - database_ignite
 

volumes:
  pgdata:
    driver: local
